### ISSUE TITLE
Blank tab when trying to run app

### ISSUE THREAD

**Issue by maacl** [chr15m/slingcode#88]
I have downloaded slingcode.html. When I try to run any app, I just get a blank tab.

I am on Ubuntu using Chrome 83.0.4. In Firefox 77.0.1 it works fine. I have attached the browser log.
[-1592989389708.log](https://github.com/chr15m/slingcode/files/4824288/-1592989389708.log)

**Comment by bryan-lott** [comment]
Likely same issue as mine, #90

**Comment by chr15m** [comment]
@maacl thanks for attaching the log. My version of Chrome is 81.0.4044.138 on Ubuntu. Could you right-click on the blank tab and view source and possibly paste the source here?

**Comment by chr15m** [comment]
@maacl have replicated this on #90 and I will close this as a duplicate. When #90 is fixed your issue should be solved. Thanks for reporting! :+1:
