### ISSUE TITLE
Use Typescript as language

### ISSUE THREAD

**Issue by icosahedron** [chr15m/slingcode#93]
Using something like ts-browser, let the user program in Typescript and transpile to Javascript.

**Comment by chr15m** [comment]
@icosahedron sounds great. Thanks for the [ts-browser library](https://github.com/klesun/ts-browser) reference. I think the only change required to Slingcode would be to syntax highlight .ts files correctly. Happy to accept a PR for this.

**Comment by icosahedron** [comment]
I'll see what I can do.  I'd love to see Clojurescript too.
